version: "2"
services:
  # このイメージのバージョンアップ = wordpress, PHPのバージョンアップ
  wordpress:
    container_name: scaffold-wp-wp
    build: ./settings/wp
    ports:
      - "9000:9000"
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
      - ./wordpress/themes/fl:/var/www/html/wp-content/themes/fl
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
      - ./tools/wordmove:/var/www/tools/wordmove
      - ./.env:/var/www/.env
    networks:
      main:
        aliases:
          - wp
  nginx:
    container_name: scaffold-wp-web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./settings/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - wordpress
    links:
      - wordpress
    networks:
      main:
        aliases:
          - web
  db:
    container_name: scaffold-wp-db
    image: mariadb:latest
    env_file: .env
    volumes:
      - ./settings/db:/etc/mysql/data
    networks:
      main:
        aliases:
          - db
networks:
  main: