version: "2"
services:
  # このイメージのバージョンアップ = wordpress, PHPのバージョンアップ
  wordpress:
    container_name: wp
    image: wordpress:php7.1-fpm-alpine
    ports:
      - "9000:9000"
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
      - ./themes/fl:/var/www/html/wp-content/themes/fl
      - ./plugins:/var/www/html/wp-content/plugins
  nginx:
    container_name: wp-web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./settings/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - wordpress
    links:
      - wordpress
  db:
    container_name: wp-db
    image: mariadb:latest
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql

# databaseのように永続的なストレージが欲しい場合に必要な設定
# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
# volumes:
#   db-data:
#     driver: local
